### ISSUE TITLE
Flash taking forever. "CPU Bootloader is not running on this device"

### ISSUE THREAD

**Issue by nightduck** [jtagxhub/jetpack-agx-build#12]
Whenever I run the flash, flash_no_rootfs, or flash_kernel commands, the process eventually hangs for half an hour at a time, cycling through:

```
[  10.9094 ] tegrarcm_v2 --isapplet
[ 1021.0857 ] 
[ 1021.0867 ] tegrarcm_v2 --ismb2
[ 2036.8937 ] 
[ 2036.9401 ] tegradevflash_v2 --iscpubl
[ 2036.9414 ] CPU Bootloader is not running on device.
[ 3052.7017 ] 
[ 3053.7042 ] tegrarcm_v2 --isapplet
[ 4068.5137 ] 
[ 4068.5151 ] tegrarcm_v2 --ismb2
[ 5084.3179 ] 
[ 5084.3190 ] tegradevflash_v2 --iscpubl
[ 5084.3199 ] CPU Bootloader is not running on device.
[ 6100.1258 ] 
[ 6101.1280 ] tegrarcm_v2 --isapplet
[ 7115.9377 ] 
[ 7115.9388 ] tegrarcm_v2 --ismb2
```

[Full trace](https://github.com/jtagxhub/jetpack-agx-build/files/4589357/flash_kernel_dump.txt)

Running lsusb shows my Nvidia device is up, so I'm assuming it's in recovery mode, and I can program from the SDK manager just fine. So it can't be the cable/USB port, right?

Flashing a Xavier AGX board.

**Comment by nightduck** [comment]
So the issue was I used jetson-agx-8gb.conf file when I should've used the jetson-agx.conf file. I'm only prompted for it the first time I run the flash command. Is there a way to change it without reinstalling everything?

**Comment by Phzera** [comment]
Hi, @nightduck , how are you?

I know that you were working on this issue more than one year ago, but by any chance did you remember how to flash prompting to a specific .conf file? 
Thank you!

**Comment by nightduck** [comment]
I believe I ran `rm build/.config` to reset the configuration, then repeated the setup steps, starting with source `build/envsetup.sh`. Lacking a config file, it'll re-prompt you for everything. You can then repeat the flash command.

I can't actually verify this is how I did it because my repo is long-gone
