### ISSUE TITLE
flash only rootfs

### ISSUE THREAD

**Issue by rjeli** [jtagxhub/jetpack-agx-build#4]
have you found a way to only flash the rootfs on the xavier? flashing the whole system takes forever

if not, i'll drudge through the nvidia flash scripts and see if it's possible

i'm worried it won't be because of some secure boot signing :worried:

**Comment by jtagxhub** [comment]
Hi Rjeli,
you could try below command under Linux_for_Tegra/
$ sudo ./flash.sh -k APP 

However, I think most of flash time are on flash rootfs, so it's not implemented.

Thanks!

**Comment by rjeli** [comment]
Finally figured it out - have to apply this patch to flash.sh: https://devtalk.nvidia.com/default/topic/1039548/jetson-agx-xavier/xavier-cloning/post/5330890/#5330890

After that, `./flash.sh -k APP` works.
