### ISSUE TITLE
Xavier 4.3 installation failing

### ISSUE THREAD

**Issue by ah-gus** [jtagxhub/jetpack-agx-build#9]
this message appears after i run bspsetup initial installation
/home/user/work/sources/kernel/kernel/kernel-4.9 check failed
_later_check failed, BSP setup failed!
NVIDIA L4T 32.3.1 or JETPACK 4.3 file locations may have changed, since no longer does it extract files under sources directory ad fails. tried to extract manually but when building kernel , for some configurations get errors and fail

**Comment by ah-gus** [comment]
choosing 4.2.3 works ok

**Comment by jtagxhub** [comment]
already fix the issue. Please try 4.3 again. The source path changes.
